import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { gsap } from "gsap"
import { useEffect, useRef } from 'react'
// import { ScrollTrigger } from 'gsap/ScrollTrigger'
// import { ScrollToPlugin } from 'gsap/ScrollToPlugin'


// gsap.registerPlugin(ScrollTrigger, ScrollToPlugin)

export default function Home() {
  const titleContainer = useRef()

  // const appear = (element, delay, duration) => {
  //   gsap.fromTo(
  //     element,
  //     {
  //       opacity: 0
  //     },
  //     {
  //       opacity: 1,
  //       delay: 0.7 || delay,
  //       duration: 0.5 || duration,
  //     }
  //   )
  // }

  const onLoad = () => {
    gsap.timeline()
      // .fromTo('#letter',
      //   {
      //     opacity: 0
      //   },
      //   {
      //     opacity: 1,
      //     stagger: 0.33,
      //     delay: 1.2,
      //   }
      // )
      .to(lineTitleSeparator,
        {
          width: "15vw",
          delay: 0.5 || delay,
          duration: 1 || duration
        }
      )
      .fromTo('#letter',
        {
          y: 19,
          opacity: 0,
        },
        {
          y: 0,
          opacity: 1,
          delay: 0.5 || delay,
          duration: 1 || duration
        }
      )
      .to('#letter',
        {
          margin: "0 0.4vw",
          duration: 0.5 || duration
        }
      )
      .to('#letter',
        {
          margin: "0 0.2vw",
          delay: 0.1 || delay,
          duration: 0.5 || duration
        }
      )
      .to(lineTitleSeparator,
        {
          y: -48,
          delay: 0.5 || delay,
          duration: 0.5 || duration
        }
      )
      .to('#letter',
        {
          y:-19,
          opacity: 0,
          duration: 0.5 || duration
        }, "<"
      )
      .to(lineTitleSeparator,
        {
          width: "0vw",
          delay: 0.5 || delay,
          duration: 1 || duration
        }
      )
  }

  useEffect(() => {
    //appear(titleContainer.current)
    onLoad()
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <svg className={styles.circle_loader_container}>
          <circle cx='25px' cy='25px' r='10px' className={styles.circle_loader}/>
        </svg> */}
        <div className={styles.title_container} ref={titleContainer}>
          <span id='letter'>B</span>
          <span id='letter'>I</span>
          <span id='letter'>E</span>
          <span id='letter'>N</span>
          <span id='letter'>V</span>
          <span id='letter'>E</span>
          <span id='letter'>N</span>
          <span id='letter'>U</span>
          <span id='letter'>E</span>
        </div>
        <div className={styles.line_title_separator} id='lineTitleSeparator' />
      </main>
    </div>
  )
}
